#!/bin/bash

psql -t \
     -o wget_links.txt \
     -q \
     -c "select hlink from dev_all_parts2 where htext = 'None' order by id_num;"






#wget -qO wget_results.html https://www.acquisition.gov/dfarspgi/pgi-part-236-construction-and-architect-\xe2\x80\x94-engineer-contracts
#
#tr -d '\n' < wget_results.html


