#!/bin/bash

file=$1
var=1

while read -r line; do
    lnk="$line"
    res=$(wget.exe -qO - $line)
    res2=$(trim -d '\n' < echo "$res")
    psql -t \
         -f ../sql/dev_variable_pass.sql \
         -v val=$res2 \
         -v idnum=$var
    let var+=1
done < $file


