#!/bin/bash

file=$1
var=1

while read -r line; do
    wget.exe -qO - $line > wget_results.html
    res=$(tr -d '\n' < wget_results.html)
    psql -t \
         -f ../sql/dev_variable_pass.sql \
         -v val=$res \
         -v idnum=$var
    let var+=1
done < $file

echo > wget_results.html

